### ISSUE TITLE
CSS/Javascript blocked on newer browsers on https://.. page

### ISSUE THREAD

**Issue by duesenfranz** [rudvfaden/rudvfaden.github.io#1]
Newer browsers, e.g. firefox automatically [block non-https resources on https sites](https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox). All your needed files (e.g. javascript, css files) are included as `http://[...].css` or similar.

This means that, when going to [https://rudvfaden.github.io/](https://rudvfaden.github.io/), the page looks rather ugly, since the css files are blocked.

It can propably be fixed by setting the url as `https://...` [here](https://github.com/rudvfaden/rudvfaden.github.io/blob/fa99d39e548e32a1557646dd086d698c9262801e/_config.yml#L9)

**Comment by rudvfaden** [comment]
seemed to work. thanks
